webdevfinal/Models/ContactFormViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace webdevfinal.Models
{
    public class ContactFormViewModel
    {
        public string Name { get; set; }
        public string Email { get; set; }
        public string Subject { get; set; }
        public string Message { get; set; }
    }
}

webdevfinal/ViewModels/ContactForm.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace webdevfinal.ViewModels
{
    public class ContactForm
    {
        public string Name { get; set; }
        public string Email { get; set; }
        public string Subject { get; set; }
        public string Message { get; set; }

    }
}

webdevfinal/Controllers/ContactFormSurfaceController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Umbraco.Web.Mvc;
using webdevfinal.ViewModels;
using Umbraco.Core.Models;



namespace webdevfinal.Controllers
{
    public class ContactFormSurfaceController : SurfaceController
    {
        // GET: Default
        public ActionResult Index()
        {
            return PartialView("ContactForm", new ContactForm());

        }
        //Comment
        [HttpPost]
        public ActionResult HandleFormSubmit(ContactForm model)
        {
            if (!ModelState.IsValid) { return CurrentUmbracoPage(); }
            // Read data from model and send
            //
            IContent comment = Services.ContentService.CreateContent(model.Subject, CurrentPage.Id, "ContactForm");
            // assign values
            comment.SetValue("name", model.Name);
            comment.SetValue("email", model.Email);
            comment.SetValue("subject", model.Subject);
            comment.SetValue("message", model.Message);
            // save to Umbraco
            Services.ContentService.Save(comment);
            // Services.ContentService.SaveAndPublish(comment);

            TempData["success"] = true;

            //RedirectToCurrentUmbracoPage: Do not keep the POST - data that was sent to the controller
            //Passes TempData from the controller
            //Use RedirectToCurrentUmbracoPage()if the post was successful
            //Prevents users from re-posting data
            return RedirectToCurrentUmbracoPage();
        }



    }
}

webdevfinal/Views/ArticleItem.cshtml
@inherits Umbraco.Web.Mvc.UmbracoTemplatePage<ContentModels.ArticleItem>
@using ContentModels = Umbraco.Web.PublishedContentModels;
@{
	Layout = "MasterLayout.cshtml";
}
<h2>@Umbraco.Field("articleTitle")</h2>
	@Umbraco.Field("articleContent")

webdevfinal/Views/ArticlesMain.cshtml
@inherits Umbraco.Web.Mvc.UmbracoTemplatePage<ContentModels.ArticlesMain>
@using ContentModels = Umbraco.Web.PublishedContentModels;
@{
	Layout = "MasterLayout.cshtml";
}


	
	
	<div class="row">
    <div class="col-md-4">
        <h2>Artikler</h2>
        <p>
            @Umbraco.Field("mainContent")
        </p>
        
    </div>
    <div class="col-md-4">
        <h2>Artikler</h2>

@{
	var selection = CurrentPage.Site().FirstChild("articlesMain").Children.Where("Visible");
}
<ul>
	@foreach(var item in selection){
		<li>
			<a href="@item.Url">@item.Name</a>
		</li>
	}
</ul>


</ul>      

    </div>
    <div class="col-md-4">
        <h2>Posuere lacinia</h2>
        <p>Urna mauris vulputate dolor, vel varius tincidunt lorem urna ut, pellentesque sodales mi pulvinar, dui a egestas, morbi nullam et aenean pharetra. Sit consectetur non, amet arcu nulla, sit porta</p>
        
			@Umbraco.RenderMacro("childpages")
    </div>
</div>

webdevfinal/Views/Comment.cshtml
@inherits Umbraco.Web.Mvc.UmbracoTemplatePage<ContentModels.Comment>
@using ContentModels = Umbraco.Web.PublishedContentModels;
@{
	Layout = null;
}

webdevfinal/Views/Contact2.cshtml
@inherits Umbraco.Web.Mvc.UmbracoTemplatePage
@{
	Layout = "MasterLayout.cshtml";
}
<div>
    @Html.Action("index", "ContactFormSurface")
</div>

webdevfinal/Views/Contact3.cshtml
@inherits Umbraco.Web.Mvc.UmbracoTemplatePage
@{
	Layout = "MasterLayout.cshtml";
}
<div>
    @Html.Action("index", "ContactFormSurface")
</div>

webdevfinal/Views/ContactPage.cshtml
@inherits Umbraco.Web.Mvc.UmbracoTemplatePage<ContentModels.ContactForm>
@using ContentModels = Umbraco.Web.PublishedContentModels;
@{
	Layout = "MasterLayout.cshtml";
}


<div>
    @Html.Action("index", "ContactFormSurface")
</div>
	@*
	@Umbraco.RenderMacro("ContactForm")
*@

webdevfinal/Views/Contactform2.cshtml
@model webdevfinal.Models.ContactFormViewModel

webdevfinal/Views/HomePage.cshtml
@inherits Umbraco.Web.Mvc.UmbracoTemplatePage<ContentModels.HomePage>
@using ContentModels = Umbraco.Web.PublishedContentModels;
@{
	Layout = "MasterLayout.cshtml";
}


<div class="row">
	<div class="col-md-4">
        <h2>@Umbraco.Field("spalte1Overkrift")</h2>
        @Umbraco.Field("mainContent")
<p>navigation macro:</p>
@Umbraco.RenderMacro("Navigation1")
</ul>
        <p><a class="btn btn-default" href="/om">Læs mere her</a></p>
    </div>
   <div class="col-md-4">
        <h2>@Umbraco.Field("spalte2Overskrift")</h2>
        <p>@Umbraco.Field("spalte2Indhold")</p>
	   
@{
	var selectiona = CurrentPage.Site().FirstChild("articlesMain").Children.Where("Visible");
}
<ul>
	@foreach(var item in selectiona){
		<li>
			<a href="@item.Url">@item.Name</a>
		</li>
	}
</ul>


        <p><a class="btn btn-default" href="/artikler">Læs mere her</a></p>
    </div><div class="col-md-4">
        <h2>@Umbraco.Field("spalte3Overskrift")</h2>
        <p>@Umbraco.Field("spalte3Indhold")</p>   
		

@{
	var selectionp = CurrentPage.Site().FirstChild("projectsMain").Children.Where("Visible");
}
<ul>
	@foreach(var item in selectionp){
		<li>
			<a href="@item.Url">@item.Name</a>
		</li>
	}
</ul>


</ul>


        <p><a class="btn btn-default" href="/projekter">Læs mere</a></p>
    </div>
</div>

webdevfinal/Views/Login.cshtml
@inherits Umbraco.Web.Mvc.UmbracoTemplatePage<ContentModels.Login>
@using ContentModels = Umbraco.Web.PublishedContentModels;
@{
	Layout = "MasterLayout.cshtml";
}
@Umbraco.RenderMacro("memberloginmacro")

webdevfinal/Views/MacroPartials/Navigation1.cshtml
@inherits Umbraco.Web.Macros.PartialViewMacroPage


@*
    This snippet displays a list of links of the pages immediately under the top-most page in the content tree.
    This is the home page for a standard website.
    It also highlights the current active page/section in the navigation with the css class "current".
*@

@{ var selection = CurrentPage.Site().Children.Where("Visible"); }

<ul>
    @foreach (var item in selection)
    {
        <li class="@(item.IsAncestorOrSelf(CurrentPage) ? "current" : null)">
            <a href="@item.Url">@item.Name</a>
        </li>
    }
</ul>

webdevfinal/Views/MacroPartials/childpages.cshtml
@inherits Umbraco.Web.Macros.PartialViewMacroPage


@{ var selection = CurrentPage.Children.Where("Visible"); }

@if (selection.Any())
{
    <ul>
        @foreach (var item in selection)
        {
            <li>
                <a href="@item.Url">@item.Name</a>
            </li>
        }
    </ul>
}

webdevfinal/Views/MacroPartials/memberloginmacro.cshtml
@inherits Umbraco.Web.Macros.PartialViewMacroPage


@using System.Web.Mvc.Html
@using ClientDependency.Core.Mvc
@using Umbraco.Web
@using Umbraco.Web.Models
@using Umbraco.Web.Controllers

@{
    var loginModel = new LoginModel();
    
    Html.EnableClientValidation();
    Html.EnableUnobtrusiveJavaScript();
    Html.RequiresJs("/umbraco_client/ui/jquery.js");
    Html.RequiresJs("/umbraco_client/Application/JQuery/jquery.validate.min.js");
    Html.RequiresJs("/umbraco_client/Application/JQuery/jquery.validate.unobtrusive.min.js");
}

@* NOTE: This RenderJsHere code should be put on your main template page where the rest of your script tags are placed *@
@Html.RenderJsHere()

@using (Html.BeginUmbracoForm<UmbLoginController>("HandleLogin"))
{
    
	<fieldset>
        <legend>Login</legend>
        
        @Html.ValidationSummary("loginModel", true)


        @Html.LabelFor(m => loginModel.Username, new { @class = "control-label" })
        @Html.TextBoxFor(m => loginModel.Username, new { @class = "form-control" })
        @Html.ValidationMessageFor(m => loginModel.Username)
        <br />

        @Html.LabelFor(m => loginModel.Password, new { @class = "control-label" })
        @Html.PasswordFor(m => loginModel.Password)
        @Html.ValidationMessageFor(m => loginModel.Password)
        <br />  <br />

        <button class="btn btn-primary input-medium pullleft">Login</button>
    </fieldset>
}

webdevfinal/Views/MasterLayout.cshtml
@inherits Umbraco.Web.Mvc.UmbracoTemplatePage
@{
    Layout = null;
}


<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@Umbraco.Field("siteTitle")</title>  
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" />
</head>
<body>				
				
	    <nav id="myNavbar" class="navbar navbar-inverse navbar-fixed-top" role="navigation">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
            
                <a class="navbar-brand" href="/">Aarhus WebDev Juni</a>
            </div>
            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                <ul class="nav navbar-nav">
                    <li><a href="/om">Om Aarhus WebDev</a></li>
                    <li><a href="/contact-us">Kontakt</a></li>
					
                    	<li class="dropdown">
                        <a href="#" data-toggle="dropdown" class="dropdown-toggle">Artikler <b class="caret"></b></a>
                        <ul class="dropdown-menu">							
						@{
						var aselection = CurrentPage.Site().FirstChild("articlesMain").Children.Where("Visible");
						}
							@foreach(var item in aselection){
							<li class="dropdown">
							<a href="@item.Url">@item.Name</a>
							</li>
							}
                    	</li>
						</ul>									
                		
							
							<li class="dropdown">
                        <a href="#" data-toggle="dropdown" class="dropdown-toggle">Projekter <b class="caret"></b></a>
                        <ul class="dropdown-menu">							
						@{
						var pselection = CurrentPage.Site().FirstChild("projectsMain").Children.Where("Visible");
						}
							@foreach(var item in pselection){
							<li class="dropdown">
							<a href="@item.Url">@item.Name</a>
							</li>
							}
                    	</li>
						</ul>									
                		</ul>
							
                <ul class="nav navbar-nav navbar-right">
                    <li class="dropdown">
                        <a href="#" data-toggle="dropdown" class="dropdown-toggle">Medlem <b class="caret"></b></a>
                        <ul class="dropdown-menu">
                            <li><a href="/memberlogin">Login</a></li>
                            <li><a href="#">Mere senere</a></li>
                            <li class="divider"></li>
                            <li><a href="#">Noget her</a></li>
                        </ul>
                    </li>
                </ul>
            </div><!-- /.navbar-collapse -->
        </div>
    </nav>
</div>
			
				
				
				
				
				
				
    <div class="container body-content">

	

</ul>

	

		
		
		
        <div class="jumbotron">
    <h1>Aarhus WebDev</h1>
    <p class="lead">Marianne's Umbraco Opgave </p>
    <p><a href="/artikler" class="btn btn-primary btn-lg">Artikler</a></p>
</div>
        @RenderBody()
        <hr />
        <footer>
            <p>@DateTime.Now.Year - - @Umbraco.Field("footer")
        </footer>
    </div>
    
    <script src="~/Scripts/jquery-2.2.1.min.js"></script>
    <script src="~/Scripts/bootstrap.min.js"></script>
    
</body>
</html>
		

webdevfinal/Views/News11.cshtml
@inherits Umbraco.Web.Mvc.UmbracoTemplatePage
@{
	Layout = "MasterLayout.cshtml";
}
@CurrentPage.GetGridHtml("Grid");

webdevfinal/Views/Partials/ContactForm.cshtml
@model webdevfinal.ViewModels.ContactForm
//model declarative. Strongly typed

<form class="form-horizontal">
   
            <div class="col-sm-6">
            @Html.TextBoxFor(m => m.Name, new {@class="form-control", placeholder = "Name" })
                    </div>      
        
        <div class="col-sm-6">
            @Html.TextBoxFor(m => m.Email, new { @class = "form-control", placeholder = "Email address" })
           
        </div>   
       
        <div class="col-sm-6">
            @Html.TextBoxFor(m => m.Subject, new { @class = "form-control", placeholder = "Subject" })
           
        </div> <div class="col-sm-6">

    @Html.TextAreaFor(m => m.Message, new { @class = "form-control", placeholder = "Your message" })
   
</div>
   
    <div class="form-group">
        <div class="col-sm-offset-2 col-sm-6">
            <button id="contact-submit" type="submit" class="btn btn-primary input-medium pullleft">Send</button>
        </div>
    </div>
</form>

webdevfinal/Views/Partials/Grid/Bootstrap2.cshtml
@inherits UmbracoViewPage<dynamic>
@using Umbraco.Web.Templates
@using Newtonsoft.Json.Linq

@* 
    Razor helpers located at the bottom of this file
*@

@if (Model != null && Model.sections != null)
{
    var oneColumn = ((System.Collections.ICollection)Model.sections).Count == 1;
    
    <div class="umb-grid">
        @if (oneColumn)
        {
            foreach (var section in Model.sections) {
                <div class="grid-section">
                    @foreach (var row in section.rows) {
                        @renderRow(row, true);
                    }
                </div>
            }   
        }else { 
            <div class="container">
                <div class="row clearfix">
                    @foreach (var s in Model.sections) {
                        <div class="grid-section">
                            <div class="@("span" + s.grid) column">
                                @foreach (var row in s.rows) {
                                    @renderRow(row, false);
                                }
                            </div>
                        </div>
                    }
                </div>
            </div>   
        }
    </div>
}

@helper renderRow(dynamic row, bool singleColumn){
    <div @RenderElementAttributes(row)>
        @Umbraco.If(singleColumn, "<div class='container'>")
        <div class="row clearfix">
            @foreach ( var area in row.areas ) {
            <div class="@("span" + area.grid) column">
                <div @RenderElementAttributes(area)>
                    @foreach (var control in area.controls) {
                        if (control !=null && control.editor != null && control.editor.view != null ) {
                            <text>@Html.Partial("grid/editors/base", (object)control)</text>
                        }
                    }
                </div>
            </div>}
        </div>
        @Umbraco.If(singleColumn, "</div>")
    </div>
}

@functions {
    public static MvcHtmlString RenderElementAttributes(dynamic contentItem)
    {
        var attrs = new List<string>();
        JObject cfg = contentItem.config;

        if(cfg != null)
            foreach (JProperty property in cfg.Properties()) {
                attrs.Add(property.Name + "=\"" + property.Value.ToString() + "\"");
            }
                
        JObject style = contentItem.styles;

        if (style != null) { 
        var cssVals = new List<string>();
        foreach (JProperty property in style.Properties())
            cssVals.Add(property.Name + ":" + property.Value.ToString() + ";");

        if (cssVals.Any())
            attrs.Add("style=\"" + string.Join(" ", cssVals) + "\"");
        }
            
        return new MvcHtmlString(string.Join(" ", attrs));
    }
}

webdevfinal/Views/Partials/Grid/Bootstrap3.cshtml
@inherits UmbracoViewPage<dynamic>
@using Umbraco.Web.Templates
@using Newtonsoft.Json.Linq

@* 
    Razor helpers located at the bottom of this file
*@

@if (Model != null && Model.sections != null)
{
    var oneColumn = ((System.Collections.ICollection)Model.sections).Count == 1;
    
    <div class="umb-grid">
        @if (oneColumn)
        {
            foreach (var section in Model.sections) {
                <div class="grid-section">
                    @foreach (var row in section.rows) {
                        @renderRow(row, true);
                    }
                </div>
            }   
        }else { 
            <div class="container">
                <div class="row clearfix">
                    @foreach (var s in Model.sections) {
                        <div class="grid-section">
                            <div class="col-md-@s.grid column">
                                @foreach (var row in s.rows) {
                                    @renderRow(row, false);
                                }
                            </div>
                        </div>
                    }
                </div>
            </div>   
        }
    </div>
}

@helper renderRow(dynamic row, bool singleColumn){
    <div @RenderElementAttributes(row)>
        @Umbraco.If(singleColumn, "<div class='container'>")
        <div class="row clearfix">
            @foreach ( var area in row.areas ) {
            <div class="col-md-@area.grid column">
                <div @RenderElementAttributes(area)>
                    @foreach (var control in area.controls) {
                        if (control !=null && control.editor != null && control.editor.view != null ) {
                            <text>@Html.Partial("grid/editors/base", (object)control)</text>
                        }
                    }
                </div>
            </div>}
        </div>
        @Umbraco.If(singleColumn, "</div>")
    </div>
}

@functions {
    public static MvcHtmlString RenderElementAttributes(dynamic contentItem)
    {
        var attrs = new List<string>();
        JObject cfg = contentItem.config;

        if(cfg != null)
            foreach (JProperty property in cfg.Properties()) {
                attrs.Add(property.Name + "=\"" + property.Value.ToString() + "\"");
            }
                
        JObject style = contentItem.styles;

        if (style != null) { 
        var cssVals = new List<string>();
        foreach (JProperty property in style.Properties())
            cssVals.Add(property.Name + ":" + property.Value.ToString() + ";");

        if (cssVals.Any())
            attrs.Add("style=\"" + string.Join(" ", cssVals) + "\"");
        }
            
        return new MvcHtmlString(string.Join(" ", attrs));
    }
}

webdevfinal/Views/Partials/Grid/Editors/Base.cshtml
@model dynamic
@using Umbraco.Web.Templates

@functions {
    public static string EditorView(dynamic contentItem)
    {
        string view = contentItem.editor.render != null ? contentItem.editor.render.ToString() : contentItem.editor.view.ToString();
        view = view.ToLower().Replace(".html", ".cshtml");
        
        if (!view.Contains("/")) {
            view = "grid/editors/" + view;
        }

        return view;
    }
}
@try
{
    string editor = EditorView(Model);                                                       
    <text>@Html.Partial(editor, (object)Model)</text>
}
catch (Exception ex) { 
<pre>@ex.ToString()</pre>
}

webdevfinal/Views/Partials/Grid/Editors/Embed.cshtml
@model dynamic
@using Umbraco.Web.Templates
@Html.Raw(Model.value)

webdevfinal/Views/Partials/Grid/Editors/Macro.cshtml
@inherits UmbracoViewPage<dynamic>
@using Umbraco.Web.Templates


@if (Model.value != null)
{
    string macroAlias = Model.value.macroAlias.ToString();
    ViewDataDictionary parameters = new ViewDataDictionary();
    foreach (dynamic mpd in Model.value.macroParamsDictionary)
    {
        parameters.Add(mpd.Name, mpd.Value);
    }

    <text>
        @Umbraco.RenderMacro(macroAlias, parameters)
    </text>
}

webdevfinal/Views/Partials/Grid/Editors/Media.cshtml
@model dynamic
@using Umbraco.Web.Templates

@if (Model.value != null)
{   
    var url = Model.value.image;
    if(Model.editor.config != null && Model.editor.config.size != null){
        url += "?width=" + Model.editor.config.size.width;
        url += "&height=" + Model.editor.config.size.height;

        if(Model.value.focalPoint != null){
            url += "&center=" + Model.value.focalPoint.top +"," + Model.value.focalPoint.left;
            url += "&mode=crop";
        }
    }
    
    <img src="@url" alt="@Model.value.altText">
    
    if (Model.value.caption != null)
    {
        <p class="caption">@Model.value.caption</p>
    }
}

webdevfinal/Views/Partials/Grid/Editors/Rte.cshtml
@model dynamic
@using Umbraco.Web.Templates

@Html.Raw(TemplateUtilities.ParseInternalLinks(Model.value.ToString()))

webdevfinal/Views/Partials/Grid/Editors/Textstring.cshtml
@model dynamic
@using Umbraco.Web.Templates

@if (Model.editor.config.markup != null)
{
    string markup = Model.editor.config.markup.ToString();

    markup = markup.Replace("#value#", Model.value.ToString());
    markup = markup.Replace("#style#", Model.editor.config.style.ToString());

    <text>
        @Html.Raw(markup)
    </text>
}
else
{
    <text>
        <div style="@Model.editor.config.style">@Model.value</div>
    </text>
}

webdevfinal/Views/Partials/View.cshtml
@model webdevfinal.ViewModels.ContactForm

webdevfinal/Views/Partials/memberlogin.cshtml
@inherits Umbraco.Web.Mvc.UmbracoTemplatePage


@using System.Web.Mvc.Html
@using ClientDependency.Core.Mvc
@using Umbraco.Web
@using Umbraco.Web.Models
@using Umbraco.Web.Controllers

@{
    var loginModel = new LoginModel();
    
    Html.EnableClientValidation();
    Html.EnableUnobtrusiveJavaScript();
    Html.RequiresJs("/umbraco_client/ui/jquery.js");
    Html.RequiresJs("/umbraco_client/Application/JQuery/jquery.validate.min.js");
    Html.RequiresJs("/umbraco_client/Application/JQuery/jquery.validate.unobtrusive.min.js");
}

@* NOTE: This RenderJsHere code should be put on your main template page where the rest of your script tags are placed *@
@Html.RenderJsHere()

@using (Html.BeginUmbracoForm<UmbLoginController>("HandleLogin"))
{
    <fieldset>
        <legend>Login</legend>
        
        @Html.ValidationSummary("loginModel", true)

        @Html.LabelFor(m => loginModel.Username)
        @Html.TextBoxFor(m => loginModel.Username)
        @Html.ValidationMessageFor(m => loginModel.Username)
        <br />

        @Html.LabelFor(m => loginModel.Password)
        @Html.PasswordFor(m => loginModel.Password)
        @Html.ValidationMessageFor(m => loginModel.Password)
        <br />

        <button>Login</button>
    </fieldset>  
}

webdevfinal/Views/ProjectItem.cshtml
@inherits Umbraco.Web.Mvc.UmbracoTemplatePage<ContentModels.ProjectItem>
@using ContentModels = Umbraco.Web.PublishedContentModels;
@{
	Layout = "MasterLayout.cshtml";
}
<h2>@Umbraco.Field("projectTitle")</H2>
@Umbraco.Field("projectDescription")
Status: @Umbraco.Field("pstatus")

webdevfinal/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    <link href="~/Content/Site.css" rel="stylesheet" type="text/css" />
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" type="text/css" />
    <script src="~/Scripts/modernizr-2.6.2.js"></script>
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Application name", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                </ul>
            </div>
        </div>
    </div>

    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    <script src="~/Scripts/jquery-1.10.2.min.js"></script>
    <script src="~/Scripts/bootstrap.min.js"></script>
</body>
</html>

webdevfinal/Views/TextPage.cshtml
@inherits Umbraco.Web.Mvc.UmbracoTemplatePage<ContentModels.TextPage>
@using ContentModels = Umbraco.Web.PublishedContentModels;
@{
	Layout = "MasterLayout.cshtml";
}
<h2>@Umbraco.Field("header")</h2>
@Umbraco.Field("mainContent")

webdevfinal/Views/nyhed.cshtml
@inherits Umbraco.Web.Mvc.UmbracoTemplatePage<ContentModels.Nyhed>
@using ContentModels = Umbraco.Web.PublishedContentModels;
@{
	Layout = null;
}